name: Knuff Said!

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  schedule:
    - cron: "*/60 * * * *" # Runs every 60 minutes

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies with npm ci
        run: npm ci

      - name: Execute Knuff
        run: node index.js reminders.yaml
        env:
          # If you only ever post reminders to the same repository
          # that runs the action, you can use the GITHUB_TOKEN automatically
          # provided by GitHub. Alternatively create a fine grained personal
          # access token with read+write issue permissions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
